// Reads images from public/images/ and converts to base64 data URLs
// Run this before rendering: node scripts/encode-images.js
// Images can have ANY filename — they are assigned to scenes in alphabetical order.
const fs = require('fs');
const path = require('path');

const imagesDir = path.join(__dirname, '../public/images');
const outputFile = path.join(__dirname, '../src/image-data.js');

const sceneSlots = [
  { key: 'scene-01-scroll',       label: 'Scene 1 – Prophecy / Scroll' },
  { key: 'scene-02-jerusalem',    label: 'Scene 2 – Jerusalem 70 AD' },
  { key: 'scene-03-spain',        label: 'Scene 3 – Spain / Portugal' },
  { key: 'scene-04-westafrica',   label: 'Scene 4 – West Africa' },
  { key: 'scene-05-maps',         label: 'Scene 5 – Ancient Maps' },
  { key: 'scene-06-slavery',      label: 'Scene 6 – Slavery / Ships' },
  { key: 'scene-07-deuteronomy',  label: 'Scene 7 – Deuteronomy 28 / Moses' },
  { key: 'scene-08-americas',     label: 'Scene 8 – The Americas' },
];

const imageExtensions = ['.png', '.jpg', '.jpeg', '.webp'];

function getMimeType(ext) {
  if (ext === '.png') return 'image/png';
  if (ext === '.webp') return 'image/webp';
  return 'image/jpeg';
}

// ── Step 1: Find ALL image files in the folder (sorted alphabetically) ──────
let allImages = [];
if (fs.existsSync(imagesDir)) {
  allImages = fs.readdirSync(imagesDir)
    .filter(f => imageExtensions.includes(path.extname(f).toLowerCase()) && !f.startsWith('.'))
    .sort();
}

console.log('');
console.log('  ==========================================');
console.log('   Encoding images into video...');
console.log('  ==========================================');
console.log('');

if (allImages.length === 0) {
  console.log('  ✗ NO IMAGES FOUND in public/images/');
  console.log('');
  console.log('  To fix: double-click OPEN IMAGES FOLDER.bat');
  console.log('  Then drag your image files into that folder.');
  console.log('  Then run ONE CLICK RENDER.bat again.');
  console.log('');
} else {
  console.log(`  Found ${allImages.length} image(s) in your folder:`);
  allImages.forEach((f, i) => console.log(`    ${i + 1}. ${f}`));
  console.log('');
}

// ── Step 2: Assign images to scenes ─────────────────────────────────────────
// Priority: exact scene name match first, then fall back to positional order.
const assignedImages = {}; // key → file path

// Pass 1: exact name matches
const remaining = [...allImages];
for (const slot of sceneSlots) {
  for (const ext of imageExtensions) {
    const exactName = slot.key + ext;
    const idx = remaining.indexOf(exactName);
    if (idx !== -1) {
      assignedImages[slot.key] = path.join(imagesDir, exactName);
      remaining.splice(idx, 1);
      break;
    }
  }
}

// Pass 2: fill unmatched slots with remaining images in order
const unfilledSlots = sceneSlots.filter(s => !assignedImages[s.key]);
for (let i = 0; i < unfilledSlots.length && i < remaining.length; i++) {
  assignedImages[unfilledSlots[i].key] = path.join(imagesDir, remaining[i]);
}

// ── Step 3: Build output ─────────────────────────────────────────────────────
let output = '// Auto-generated by scripts/encode-images.js — do not edit manually\n';
output += '// Run ONE CLICK RENDER.bat to regenerate with your images\n';
output += 'export const IMAGES = {\n';

let found = 0;
let missing = 0;

for (const slot of sceneSlots) {
  const filePath = assignedImages[slot.key];
  if (filePath && fs.existsSync(filePath)) {
    const ext = path.extname(filePath).toLowerCase();
    const mimeType = getMimeType(ext);
    const buffer = fs.readFileSync(filePath);
    const data = buffer.toString('base64');
    output += `  '${slot.key}': 'data:${mimeType};base64,${data}',\n`;
    console.log(`  ✓ ${slot.label}`);
    console.log(`       Using: ${path.basename(filePath)}`);
    found++;
  } else {
    output += `  '${slot.key}': null,\n`;
    console.log(`  ✗ ${slot.label} — no image (dark background)`);
    missing++;
  }
}

output += '};\n';

fs.writeFileSync(outputFile, output);

console.log('');
if (found === 0) {
  console.log('  ⚠  No images were encoded. Video will have dark backgrounds.');
  console.log('');
  console.log('  FIX: Double-click "OPEN IMAGES FOLDER.bat",');
  console.log('       drag your images in, then re-run ONE CLICK RENDER.bat');
} else if (missing > 0) {
  console.log(`  Done! ${found} image(s) encoded, ${missing} scene(s) will be dark.`);
  console.log('  You can add more images later and re-render.');
} else {
  console.log(`  Done! All ${found} images encoded successfully!`);
}
console.log('');
