// Auto-generated by scripts/encode-images.js — do not edit manually
// Run ONE CLICK RENDER.bat to regenerate with your images
export const IMAGES = {
  'scene-01-scroll': null,
  'scene-02-jerusalem': null,
  'scene-03-spain': null,
  'scene-04-westafrica': null,
  'scene-05-maps': null,
  'scene-06-slavery': null,
};
